# Generated by Django 4.2.2 on 2023-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=800)),
                ('short_url', models.URLField(max_length=100)),
                ('date_time_created', models.DateTimeField()),
            ],
        ),
    ]
